# Generated by Django 2.0.5 on 2018-05-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('players', models.ManyToManyField(related_name='tournaments', to='mtg_pairings.Player')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='mtg_pairings.Tournament'),
        ),
        migrations.AddField(
            model_name='duel',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ones', to='mtg_pairings.Player'),
        ),
        migrations.AddField(
            model_name='duel',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_twos', to='mtg_pairings.Player'),
        ),
        migrations.AddField(
            model_name='duel',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels', to='mtg_pairings.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('tournament', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='duel',
            unique_together={('player_1', 'player_2', 'round'), ('player_2', 'player_1', 'round')},
        ),
    ]
