# Generated by Django 2.0.5 on 2018-05-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_pairings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='player_1_wins',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='player_2_wins',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
