# Generated by Django 2.0.13 on 2019-04-10 12:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


def generate_teams(apps, schema_editor):
    Tournament = apps.get_model('mtg_pairings', 'Tournament')
    for tournament in Tournament.objects.filter(teams={}):
        teams = {player.name: [player.name] for player in tournament.players.all()}
        print(teams)
        tournament.teams = teams
        tournament.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_pairings', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.RunPython(generate_teams, reverse_code=migrations.RunPython.noop),
    ]
