# Generated by Django 2.0.5 on 2018-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_pairings', '0003_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='player_1_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='duel',
            name='player_2_wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='duel',
            unique_together={('player_2', 'round'), ('player_1', 'round')},
        ),
    ]
