# Generated by Django 2.0.5 on 2018-05-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_pairings', '0004_auto_20180516_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-date']},
        ),
    ]
