# Generated by Django 2.0.13 on 2019-05-03 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_pairings', '0004_auto_20190426_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
