# Generated by Django 2.0.5 on 2018-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_pairings', '0005_auto_20180517_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
